# Generated by Django 2.0 on 2018-04-12 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marjamehu', '0002_auto_20180411_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
    ]
