# Generated by Django 2.0 on 2018-04-12 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marjamehu', '0004_customuser_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='GAME',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_url', models.CharField(max_length=255)),
                ('game_name', models.CharField(max_length=100, unique=True)),
                ('game_price', models.PositiveIntegerField()),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
